Minimal reproduction: Turbopack panics on ** operator with styledComponents
Turbopack's SWC ES2015 generator transform has a todo!() for the **
(exponentiation) operator, which is the only right-associative binary
operator in JavaScript. When compiler.styledComponents is enabled and
node_modules contain **, the transform panics.

Panic: swc_ecma_compat_es2015/src/generator.rs:507
Error: "not yet implemented: right-associative binary expression"